### ISSUE TITLE
Trained model release

### ISSUE THREAD

**Issue by SerhiiPostupaiev** [YilinLiu97/FasterDIP-devil-in-upsampling#2]
Hi, are you planning to release the trained model?

**Comment by YilinLiu97** [comment]
Hi, since DIP re-trains a model anew for every image, we are not releasing the pre-trained models as that will be too many. However, replicating the results should be straightforward, please see #1 for details.

**Comment by SerhiiPostupaiev** [comment]
Thank you for the quick response :)
