### ISSUE TITLE
May I ask you some questions

### ISSUE THREAD

**Issue by WangYu0431** [YilinLiu97/FasterDIP-devil-in-upsampling#3]
Dear Dr. Liu,
I hope this message finds you well. I wanted to follow up on the email I sent to you yesterday to inquire if you had the chance to review it. I am eager to seek your guidance on a few matters and would greatly appreciate your assistance.
Please let me know at your earliest convenience if it is convenient for you to discuss the questions I have in mind.
Thank you for your attention, and I look forward to your prompt response.

**Comment by YilinLiu97** [comment]
Your question in the email is related to ISNAS-DIP, not ours. Please refer to [their repository](https://github.com/ozgurkara99/ISNAS-DIP) for help.

**Comment by WangYu0431** [comment]
I hope this message finds you well. I wanted to extend my sincere apologies if I have been causing any disruptions or inconveniences with my recent communications. Please accept my apologies for any unintended disturbances.



王宇
yu.


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YilinLiu97/FasterDIP-devil-in-upsampling"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月7日(星期二) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YilinLiu97/FasterDIP-devil-in-upsampling] May I ask you some questions (Issue #3)





 
Your question in the email is related to ISNAS-DIP, not ours. Please refer to their repository for help.
